### ISSUE TITLE
Move contents of all 3 private functions from info.inc back into the .module file.

### ISSUE THREAD

**Issue by jenlampton** [kthull/google_tag#3]
In the module file there are three hook implementations that like this:
```
function google_tag_menu() {
  module_load_include('inc', 'google_tag', 'includes/info');
  return _google_tag_menu();
}
```
These 3 private functions that start with `_google_tag...` are located in the .info.inc file, but do not appear to be shared across multiple calling locations. 

This kind of code division makes sense when the code is shared, but can make the code hard to read and hard to work with. We should move the code from each of these private functions back into each calling hook, remove the private functions, and delete the `info.inc` file.

**Comment by kthull** [comment]
Addressed with this commit: https://github.com/kthull/google_tag/commit/c844a58c1e562853b0004126b03e33b70c28971e
