### ISSUE TITLE
Move hook_variable_* functions in to a google_tag.variable.inc file, or remove

### ISSUE THREAD

**Issue by jenlampton** [kthull/google_tag#4]
The implementations of `hook_variable_info`, `hook_variable_group_info` and `hook_variable_type_info`, if they exist, should be moved into a `google_tag.variable.inc` file, to indicate that they belong to the Variable module.

The same is true for `google_tag_form_variable_edit_form_alter()` but since it's a `form_alter` and `google_tag_form_variable_realm_edit_variables_form_alter()` functions.

I expect that the Variable module may never come to exist for Backdrop, since we now have popper configuration management, so it might even be safe to remove these functions entirely.

**Comment by kthull** [comment]
Looking at this more, I'm thinking this whole variables file needs to be moved into the admin file as a `hook_admin_settings` function with an accompanying form validation function.
