### ISSUE TITLE
Replace hook_page_build() with hook_preprocess_page()

### ISSUE THREAD

**Issue by jenlampton** [kthull/google_tag#5]
We removed hook_page_build in backdrop, so adding the variables to the page will need to be done a different way than it was in Drupal. 

The recommended approach for adding JS to the page in Backdrop is to use hook_preprocess_page() instead.

See https://api.backdropcms.org/change-records/new-layout-module-implements-drag-drop-model-building-layouts for complete details of the API change.

The page_build function looks like a bit of a doozy, but as far as I can tell the only part that will need to change to work with preprocess is the part of the page it was adeded into. `$page['page_top']` will need to be something like `$varaiables['page_bottom']`.

**Comment by kthull** [comment]
Added via this commit: https://github.com/kthull/google_tag/commit/d15b5e31ee8dbde76f0b6c0efe95e2ffd3206139
