### ISSUE TITLE
Remove 3rd parameter from all config_get() calls

### ISSUE THREAD

**Issue by jenlampton** [kthull/google_tag#6]
The biggest difference between `variable_get()` and 'config_get()` is that variable get included a default value as the last parameter. For  `config_get()` the default is instead set in a `config/google_tag.settings.json` file that is included with the module. Which has already been started! :)

In order for this to be loaded along with the module, you'll also need to add an implementation of `hook_config_info()`. The below should do the trick.

```
/**
 * Implements hook_config_info().
 */
function google_tag_config_info() {
  $prefixes['google_tag.settings'] = array(
    'label' => t('Google Tag Manager settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}
```

**Comment by kthull** [comment]
I pushed a commit for this: https://github.com/kthull/google_tag/commit/4b143d78fa709e82e03f58378cb2ff7cc1b10ec8

**Comment by kthull** [comment]
Missed one, which is part of this commit: https://github.com/kthull/google_tag/commit/4037bd3c3757b9050f3303659df9469a5d9b4187
