### ISSUE TITLE
Remove variable deletes from uninstall hook

### ISSUE THREAD

**Issue by jenlampton** [kthull/google_tag#7]
Since we've converted from varaibles to config, we don't need to delete anything from the variables table on uninstall. These three lines can be removed:

```
    db_delete('variable_store')
      ->condition('name', db_like('google_tag_') . '%', 'LIKE')
      ->execute();
```

**Comment by kthull** [comment]
Addressed here (the whole following if statement was also looking to delete vars, so I killed that as well): https://github.com/kthull/google_tag/commit/4037bd3c3757b9050f3303659df9469a5d9b4187
