### ISSUE TITLE
Move + Rename files in /includes/ directory

### ISSUE THREAD

**Issue by jenlampton** [kthull/google_tag#9]
There are files in the `includes` directory that should be moved and renamed to match coding standards. `includes/admin.inc` should be renamed to 'google_tag.admin.inc` to be consistent with all other contrib projects. 

See https://api.backdropcms.org/modules, the "Contents of the Module directory" section, for an example and https://api.backdropcms.org/php-standards#naming-conventions for an explanation.

**Comment by kthull** [comment]
Addressed with this commit: https://github.com/kthull/google_tag/commit/b2f0a6086fdbef91e33c51cd2c1a9c61477a1433
